/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkRouteImport } from './routes/work'
import { Route as Agents44B2B01RouteImport } from './routes/agents/44-B2B-01'
import { Route as Agents44CIN03RouteImport } from './routes/agents/44-CIN-03'
import { Route as Agents44LCB02RouteImport } from './routes/agents/44-LCB-02'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const Agents44B2B01Route = Agents44B2B01RouteImport.update({
  id: '/agents/44-B2B-01',
  path: '/agents/44-B2B-01',
  getParentRoute: () => rootRouteImport,
} as any)
const Agents44CIN03Route = Agents44CIN03RouteImport.update({
  id: '/agents/44-CIN-03',
  path: '/agents/44-CIN-03',
  getParentRoute: () => rootRouteImport,
} as any)
const Agents44LCB02Route = Agents44LCB02RouteImport.update({
  id: '/agents/44-LCB-02',
  path: '/agents/44-LCB-02',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work': typeof WorkRoute
  '/agents/44-B2B-01': typeof Agents44B2B01Route
  '/agents/44-CIN-03': typeof Agents44CIN03Route
  '/agents/44-LCB-02': typeof Agents44LCB02Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work': typeof WorkRoute
  '/agents/44-B2B-01': typeof Agents44B2B01Route
  '/agents/44-CIN-03': typeof Agents44CIN03Route
  '/agents/44-LCB-02': typeof Agents44LCB02Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work': typeof WorkRoute
  '/agents/44-B2B-01': typeof Agents44B2B01Route
  '/agents/44-CIN-03': typeof Agents44CIN03Route
  '/agents/44-LCB-02': typeof Agents44LCB02Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/work'
    | '/agents/44-B2B-01'
    | '/agents/44-CIN-03'
    | '/agents/44-LCB-02'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/work'
    | '/agents/44-B2B-01'
    | '/agents/44-CIN-03'
    | '/agents/44-LCB-02'
  id:
    | '__root__'
    | '/'
    | '/work'
    | '/agents/44-B2B-01'
    | '/agents/44-CIN-03'
    | '/agents/44-LCB-02'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkRoute: typeof WorkRoute
  Agents44B2B01Route: typeof Agents44B2B01Route
  Agents44CIN03Route: typeof Agents44CIN03Route
  Agents44LCB02Route: typeof Agents44LCB02Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/44-B2B-01': {
      id: '/agents/44-B2B-01'
      path: '/agents/44-B2B-01'
      fullPath: '/agents/44-B2B-01'
      preLoaderRoute: typeof Agents44B2B01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/44-CIN-03': {
      id: '/agents/44-CIN-03'
      path: '/agents/44-CIN-03'
      fullPath: '/agents/44-CIN-03'
      preLoaderRoute: typeof Agents44CIN03RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/44-LCB-02': {
      id: '/agents/44-LCB-02'
      path: '/agents/44-LCB-02'
      fullPath: '/agents/44-LCB-02'
      preLoaderRoute: typeof Agents44LCB02RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkRoute: WorkRoute,
  Agents44B2B01Route: Agents44B2B01Route,
  Agents44CIN03Route: Agents44CIN03Route,
  Agents44LCB02Route: Agents44LCB02Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
